"""1.3.6

新增转移账本表 TRANSFER_LEDGER，用于记录已转移过的种子、跳过重复整理。

替代旧版「往下载器打 已整理 标签」的做法（该做法在 qBittorrent 上从未真正生效）。
仅新建表，不改动任何既有表结构。

Revision ID: 89ea3ada7589
Revises: d116d793ba9f
Create Date: 2026-09-22 06:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ea3ada7589'
down_revision = 'd116d793ba9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_table(
            'TRANSFER_LEDGER',
            sa.Column('ID', sa.Integer(), nullable=False),
            sa.Column('DOWNLOADER', sa.Text(), nullable=True),
            sa.Column('TORRENT_ID', sa.Text(), nullable=True),
            sa.Column('PATH', sa.Text(), nullable=True),
            sa.Column('DATE', sa.Text(), nullable=True),
            sa.PrimaryKeyConstraint('ID')
        )
        op.create_index('ix_TRANSFER_LEDGER_DOWNLOADER', 'TRANSFER_LEDGER', ['DOWNLOADER'])
        op.create_index('ix_TRANSFER_LEDGER_TORRENT_ID', 'TRANSFER_LEDGER', ['TORRENT_ID'])
        op.create_index('ix_TRANSFER_LEDGER_DATE', 'TRANSFER_LEDGER', ['DATE'])
    except Exception:
        # 表已存在（例如由 create_all 先建好）时忽略
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_table('TRANSFER_LEDGER')
    except Exception:
        pass
    # ### end Alembic commands ###
