"""1.3.8

Revision ID: a7e21c4b9d38
Revises: b7c1e9f40a12
Create Date: 2026-10-08 06:45:00.000000

目录同步（CONFIG_SYNC_PATHS）新增两个列：

    SCRAPE    —— 刮削策略。1=刮削新的信息；0=复用目录中已有的 nfo/图片，不再重新刮削。
                 为空（历史数据）时按 1 处理，保持原有行为。
    OVERWRITE —— 目的文件已存在时的处理。1=删除媒体库中的原有文件并用新文件替换；
                 0=跳过。为空（历史数据）时按 0 处理，保持原有行为。

⚠️ 本仓每次启动都会 `delete from alembic_version` 后重跑全部迁移
（见 app/db/main_db.py），所以迁移体必须**幂等**：两个 add_column 都用
try/except 包住，重复执行只是抛「列已存在」然后被吞掉。
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e21c4b9d38'
down_revision = 'b7c1e9f40a12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("CONFIG_SYNC_PATHS") as batch_op:
            batch_op.add_column(sa.Column('SCRAPE', sa.Integer, nullable=True))
    except Exception:
        pass
    try:
        with op.batch_alter_table("CONFIG_SYNC_PATHS") as batch_op:
            batch_op.add_column(sa.Column('OVERWRITE', sa.Integer, nullable=True))
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_column('CONFIG_SYNC_PATHS', 'SCRAPE')
    except Exception:
        pass
    try:
        op.drop_column('CONFIG_SYNC_PATHS', 'OVERWRITE')
    except Exception:
        pass
    # ### end Alembic commands ###
