"""1.3.7

Revision ID: b7c1e9f40a12
Revises: 89ea3ada7589
Create Date: 2026-09-23 16:30:00.000000

刷流任务新增「任务时长」两个列：
    TASK_DURATION —— 单位小时（支持小数，如 0.5 / 2 / 24），空 = 不限时
    START_TIME    —— 计时起点。任务状态变为 Y（正常）时写入，非 Y 时清空

⚠️ 本仓每次启动都会 `delete from alembic_version` 后重跑全部迁移
（见 app/db/main_db.py），所以迁移体必须**幂等**：两个 add_column 都用
try/except 包住，重复执行只是抛「列已存在」然后被吞掉。
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c1e9f40a12'
down_revision = '89ea3ada7589'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("SITE_BRUSH_TASK") as batch_op:
            batch_op.add_column(sa.Column('TASK_DURATION', sa.Text, nullable=True))
    except Exception as e:
        pass
    try:
        with op.batch_alter_table("SITE_BRUSH_TASK") as batch_op:
            batch_op.add_column(sa.Column('START_TIME', sa.Text, nullable=True))
    except Exception as e:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SITE_BRUSH_TASK', 'TASK_DURATION')
    op.drop_column('SITE_BRUSH_TASK', 'START_TIME')
    # ### end Alembic commands ###
